_BASE_: "Base-MEInst.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  MEInst:
    DIM_MASK: 60
    MASK_SIZE: 28
    USE_DEFORMABLE: True
    LAST_DEFORMABLE: True
    TYPE_DEFORMABLE: "DCNv1"
SOLVER:
  STEPS: (180000, 240000)
  MAX_ITER: 270000
OUTPUT_DIR: "output/MEInst/R_50_3x"
