FROM mirrors.tencent.com/rpf_detectronv2/rpf_detectronv2_oym:version1.0
RUN pip3 install shapely,Levenshtein
RUN python3 -m pip install 'git+https://github.com/facebookresearch/detectron2.git'
RUN python3 -m pip install 'git+https://github.com/Megvii-BaseDetection/cvpods.git'

