_BASE_: "Base-CondInst.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  CONDINST:
    MASK_BRANCH:
      SEMANTIC_LOSS_ON: None

  OYOR:
    ASSIGN: 'OYOR'
    AUX_ON: True
    CENTER_SAMPLING_RADIUS: 1.5
    MASK_BETA: 0.9
    SCORE_THRESH_TEST: 0.025
    INFERENCE_TH_TEST: 0.025

  FCOS:
    SCORE_THRESH_TEST: 0.025
    TOPK_CANDIDATES_TEST: 100


#DATASETS:
#  TEST: ("coco_2017_test-dev",)

TEST:
  EVAL_PERIOD : 14000

SOLVER:
  CHECKPOINT_PERIOD: 7000
  STEPS: (480000, 520000)
  MAX_ITER: 540000



