_BASE_: "../Base-FCOS.yaml"
INPUT:
  MIN_SIZE_TRAIN: (256, 288, 320, 352, 384, 416, 448, 480, 512, 544, 576, 608)
  MAX_SIZE_TRAIN: 900
  MAX_SIZE_TEST: 736
  MIN_SIZE_TEST: 512
MODEL:
  BACKBONE:
    NAME: "build_fcos_dla_fpn_backbone"
    FREEZE_AT: -1
  WEIGHTS: "http://dl.yf.io/dla/models/imagenet/dla34-ba72cf86.pth"
  DLA:
    CONV_BODY: "DLA34"
    NORM: "SyncBN"
  FPN:
    IN_FEATURES: ["level3", "level4", "level5"]
  FCOS:
    TOP_LEVELS: 0
    SIZES_OF_INTEREST: [64, 128]
    FPN_STRIDES: [8, 16, 32]
    IN_FEATURES: ['p3', 'p4', 'p5']
    NUM_SHARE_CONVS: 4
    NUM_BOX_CONVS: 0
    NUM_CLS_CONVS: 0
SOLVER:
  STEPS: (300000, 340000)
  MAX_ITER: 360000
OUTPUT_DIR: "output/fcos/FCOS_RT_MS_DLA_34_4x_syncbn_shared_towers"
