_BASE_: "Base-CondInst.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
SOLVER:
  STEPS: (420000, 500000)
  MAX_ITER: 540000
OUTPUT_DIR: "output/condinst_MS_R_50_3x"
