_BASE_: "Base-Panoptic.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
    DEFORM_ON_PER_STAGE: [False, True, True, True]
    DEFORM_MODULATED: True
    DEFORM_INTERVAL: 3
SOLVER:
  STEPS: (280000, 360000)
  MAX_ITER: 400000
INPUT:
  MIN_SIZE_TRAIN: (640, 864)
  MIN_SIZE_TRAIN_SAMPLING: "range"
  MAX_SIZE_TRAIN: 1440
  CROP:
    ENABLED: True
OUTPUT_DIR: "output/panoptic/blendmask/R_50_dcni3_5x"
